### PR TITLE
Add environment badge to README

### PR DESCRIPTION
**Pull request by szepeviktor**
image

### CODE REVIEW

**Comment by adamlaki** [comment]
Viktor, this development domain will be invalid once we move to the live domain. We can test any preview on netlify so we don't need separate dev environment. 

Does this badge has any value in this case?

**Comment by szepeviktor** [comment]
1. The viktor-killer question: _What's the value?_
2. I would like you to be an [environment](https://cone-development-site.netlify.app/) lover! Always deploy to a non-prod environment before _going live_. Even in case of _el cheapo_ WP projects. 🙃 Spend time on extra deployment -> get old sooner

**Comment by adamlaki** [comment]
Vikor, in case of netlify your server both can be a staging and prod if you turn of the auto publishing.

Value: in the prevously mentioned case.

**Comment by szepeviktor** [comment]
@adamlaki Úgy hiányzik nekem ez a badge.
Nincs mire klattyinccsak!!

**Pull request closed without merging**
