### PR TITLE
Check links with Lychee

### PR DESCRIPTION
**Pull request by szepeviktor**
@adamlaki I let you benefit from it and configure Lychee.
https://github.com/conedevelopment/cone-site/actions/runs/6604189664#summary-17938069955 💰

### CODE REVIEW

**Comment by adamlaki** [comment]
Thanks, Viktor!

It seems that there are some false results:

image

**Comment by szepeviktor** [comment]
All right.

Please configure Lychee.
I want you to like it!

**Comment by szepeviktor** [comment]
Maybe setting a Google Chrome UA will help it, or you can ignore this website in `.lycheeignore`.
https://github.com/lycheeverse/lychee#commandline-parameters
But if you have no extra time for quality assurance tools ...

**Comment by szepeviktor** [comment]
I am not able to fix 404-s. Please help me.
https://github.com/conedevelopment/cone-site/actions/runs/6605210781#summary-17940150155
This is a possible fix
https://web.archive.org/web/20160420235805/http://adamlaki.com/relativ-viewport-mertekegysegek/

**Comment by adamlaki** [comment]
Thank you, Viktor; I will come back here in the near future and merge it. ❤️

**Comment by adamlaki** [comment]
Also, Lychee looks cool (it can find the broken links 🤯); I like it already.

**Comment by szepeviktor** [comment]
@adamlaki Could we work on the remaining 2 broken links?

**Comment by adamlaki** [comment]
Thanks, Viktor! I've merged it because I couldn't retest it or see the previous log.

**Comment by szepeviktor** [comment]
Glad to see things are in progress.

**Pull request merged**
