### PR TITLE
Add yamllint to test.yml

### PR DESCRIPTION
**Pull request by szepeviktor**
Extra bonus 🎁 indentation.

From https://github.com/conedevelopment/cone-site/pull/14#issuecomment-1697266260

### CODE REVIEW

**Comment by szepeviktor** [comment]
We need 2 jobs as `npm ci` adds a lot of files.

**Comment by adamlaki** [comment]
Thank you Viktor!

**Comment by adamlaki** [comment]
Can the yamllint give back better error message?

image

**Comment by szepeviktor** [comment]
> Can the yamllint give

It adds GitHub Annotation.
See the diffs!
e.g. https://github.com/conedevelopment/cone-site/pull/16/files

Actually all proper tools add annotations.

**Comment by szepeviktor** [comment]
`on` needs a `disable-line`
```yaml
on:  # yamllint disable-line rule:truthy
```

**Comment by szepeviktor** [comment]
It is beneficial to work in PR-s. Even if you work alone.

**Comment by adamlaki** [comment]
Okay, thank you!

I start to lost my love for yamllint. Can I specify that I only want to validate in my front-matter (between ---)?

**Comment by adamlaki** [comment]
@szepeviktor So, the only thing that we can enable here is the indentation but for that the editor config is enough (as I see). This breaks at to many places: https://github.com/conedevelopment/cone-site/actions/runs/6012076151/job/16306722133

Places that I can't or won't fix.

**Comment by szepeviktor** [comment]
Sad news https://github.com/adrienverge/yamllint/issues/161

Could you take a look at `yq`? Can it extract Front Matter only?

**Comment by adamlaki** [comment]
No, I couldn't find anything. It seems that just with the config file you can't.

**Comment by szepeviktor** [comment]
Okay. I will research how `yq` can extract Front Matter from Markdown documents.
https://mikefarah.gitbook.io/yq/usage/front-matter

**Pull request merged**
