### PR TITLE
Translate "Which plugins"

### PR DESCRIPTION
**Pull request by szepeviktor**
And a typo fix as an extra bonus 🎁

### CODE REVIEW

**Comment by szepeviktor** [comment]
@iamgergo If you write English text please consider copy-pasting it into Grammarly or DeepL Write.

It is slow ❌💰 but feels good ☺️

**Comment by szepeviktor** [comment]
@adamlaki Friendly ping 🏓

**Comment by adamlaki** [comment]
Thank you Viktor!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
