### PR TITLE
Use 4 space indentation in Front Matter

### PR DESCRIPTION
**Pull request by szepeviktor**
From #4
Review without whitespace changes: https://github.com/conedevelopment/cone-site/pull/14/files?diff=unified&w=1
And the split view: https://github.com/conedevelopment/cone-site/pull/14/files?diff=split&w=0

Would you like a CI workflow
- for Front Matter [YAML](https://github.com/szepeviktor/byte-level-care/blob/3f9e004307fb0978b56cc0608588225934ecdbf1/.github/workflows/yaml.yml#L33)?
- for Markdown?

### CODE REVIEW

**Comment by adamlaki** [comment]
image

@szepeviktor shouldn't this be 8 space?

**Comment by szepeviktor** [comment]
This is NOT a viktor invention!
Please see the YAML Specs https://yaml.org/spec/1.2.2/#21-collections
Even though GitHub and other platforms are recommending an artistic way to generate emotions.

image

**Comment by szepeviktor** [comment]
I cannot stop anyone from being a Artist.
But I choose to be an expert without any kind of art.

# ❌🎨

**Comment by adamlaki** [comment]
Well, I kind of start to like this styleguide. How can I lint it on local?

**Comment by szepeviktor** [comment]
> How can I lint it on local?

With the [same tool](https://github.com/adrienverge/yamllint) as in CI: https://github.com/szepeviktor/byte-level-care/blob/3f9e004307fb0978b56cc0608588225934ecdbf1/.github/workflows/yaml.yml#L47-L50
I hope you have Python on your machine.

Here is my _one size fits none_ config.
https://github.com/szepeviktor/byte-level-care/blob/master/.yamllint.yml

**Comment by adamlaki** [comment]
I will look into it soon and get back to you! Thank you!

**Comment by szepeviktor** [comment]
> Well, I kind of start to like this styleguide.

BTW I cannot get used to it! `yamllint` always hits me over the head.

**Comment by adamlaki** [comment]
Which part you can't get used to it? The structured YAML?

**Comment by szepeviktor** [comment]
> The structured YAML?

Yes.

**Comment by adamlaki** [comment]
Viktor,

I could run yamllint with this package: https://www.npmjs.com/package/yaml-lint

Do I need a config file because the linted files are correct?

**Comment by adamlaki** [comment]
Found it, sorry: https://github.com/szepeviktor/byte-level-care/blob/master/.yamllint.yml

**Comment by szepeviktor** [comment]
> I could run yamllint with this package: https://www.npmjs.com/package/yaml-lint

Please do not let your computer influence you!!
That "yamllint" has 57 stars.
https://github.com/adrienverge/yamllint has 2500 stars.
I could send a [blond 👱🏻‍♀️ sysadmin](https://media.licdn.com/dms/image/C5603AQELlRKG-73LZA/profile-displayphoto-shrink_800_800/0/1648662603592?e=2147483647&v=beta&t=E6Mf0e2FC6opXNDME2qPf9K14eeA4TkLw33CHehI8hI) to install Python on your machine.

**Comment by adamlaki** [comment]
Yeah, you are right. I didn't get any luck with the npm package.

Python is installed (yamllint package also). Unfortunately, I can't run the command on windows (not recognized command).

**Comment by adamlaki** [comment]
image

It seems that python/pip is installed correctly but for some reason I couldn't find the yamllint command that is clearly listed and installed.

**Comment by szepeviktor** [comment]
You find this link above
https://github.com/szepeviktor/byte-level-care/blob/3f9e004307fb0978b56cc0608588225934ecdbf1/.github/workflows/yaml.yml#L47-L50

`python -m yamllint ./munkaink.md`

**Comment by adamlaki** [comment]
Thank you Viktor! It works. 

image

Do you have any idea for this?

**Comment by adamlaki** [comment]
Got it: 
image

**Comment by szepeviktor** [comment]
With yamllint you could fine-tune every single character in your YAML files 🤩

**Comment by adamlaki** [comment]
@szepeviktor Viktor, can you update this at the test workflow?

**Comment by szepeviktor** [comment]
> update this

Do you mean indenting all files with 4 spaces
or adding yamllint to the workflow?

**Comment by adamlaki** [comment]
yamllint to the workflow!

**Comment by szepeviktor** [comment]
Viktor is your copy-paster guy!

**Pull request merged**
