### PR TITLE
Lint Front Matter

### PR DESCRIPTION
**Pull request by szepeviktor**
1. Remove the contents from Markdown files
2. Run `yamllint` on the rest of the document, thus the Front Matter

### CODE REVIEW

**Comment by szepeviktor** [comment]
YAML files could also be checked!
```
.github/workflows/test.yml
.yamllint.yml
```

**Comment by adamlaki** [comment]
So, Viktor... You did it? 👀

**Comment by szepeviktor** [comment]
[_I think I did it again_](https://youtu.be/vC3Jmj9Klgg?t=82)

**Comment by adamlaki** [comment]
Let's see Viktor, thank you very much the for the effort and work!

**Pull request merged**
